### ISSUE TITLE
Do you use Faker?

### ISSUE THREAD

**Issue by ruralocity** [everydayrails/rails-5.0-rspec-3.5#1]
I'm wondering whether I should include a section on Faker in the next version of [Everyday Rails Testing with RSpec](http://rspectutorial.com). If you've read the book, have you gone on to use Faker in your own projects? Or do you think the section is unnecessary?

**Comment by Freika** [comment]
Yes and no. Faker is cool but now I prefer FFaker which is wider and provides more entities.

**Comment by andyw8** [comment]
I don't like seeing Faker uses in automated tests since it introduces randomness. I want my tests to be fully deterministic.

**Comment by JunichiIto** [comment]
I think Faker is useful in seeds.rb because it generates interesting sample data (like user name, address, email, etc.) But in tests I have the same opinion as @andyw8 .

> Or do you think the section is unnecessary?

Maybe unnecessary. But it might be worth mentioning in columns or something.

**Comment by ruralocity** [comment]
Thanks @Freika @andyw8 @JunichiIto for your input. I agree that Faker is unnecessary. I liked it when I was learning, but I don't use it today. I'm going to remove the section on it from chapter 4.
